### ISSUE TITLE
Can we use this to learn the weights for soft rules?

### ISSUE THREAD

**Issue by domoritz** [samidhtalsania/lpmln#2]
This program looks fantastic and I wonder whether I can use it for a problem I want to solve. I have a large number of input/output examples for an asp program with weight rules. I'd like to learn the weights such that the program produces the desired output for all my examples. How would I use lpmln to do this?

**Comment by samidhtalsania** [comment]
Currently, this implementation does not support weight learning. 

However, [Dr. Joohyung Lee](mailto:joolee@asu.edu) and [Yi Wang](ywang485@asu.edu) are working on it and would be better suited to answer your question since it relates to learning weights. 

Once the weights are learned, you can use this program.

**Comment by domoritz** [comment]
Thank you for the prompt response! I will get in touch with them to ask about it.
